### ISSUE TITLE
Cannot start new repo.

### ISSUE THREAD

**Issue by ctrlShiftBryan** [PhilDL/remix-gospel-stack#136]
Unable to start a new project with this template:

Nodejs: `v20.10.0`

```
 remix   v2.8.1 💿 Let's build a better website...

   dir   Where should we create your new project?
         my-repo

      ◼  Template: Using https://github.com/PhilDL/remix-gospel-stack...
      ✔  Template copied

   git   Initialize a new git repository?
         No

      ✔  Dependencies installed
      ✔  Dependencies for remix.init script installed

      ◼  Running template's remix.init script...

      ◼  What is the name of the monorepo @org? @my-org
      ◼  Which database do you want to use? (Deployed to Fly.io)       PostgreSQL

      ◼  Preparing monorepo for postgres...

      ▲  Oh no! Template's remix.init script failed
  ```
  
  Trying to clone and run the script I get more detail:
  ```
  Progress: resolved 1789, reused 1669, downloaded 0, added 2109, done
Done in 11.3s
      ◼  What is the name of the monorepo @org? @remix-gospel-stack
      ◼  Which database do you want to use? (Deployed to Fly.io)       PostgreSQL
      ◼  Preparing monorepo for postgres...
Error: 🚨 Oops, remix.init failed

No files match the pattern: /Users/myuser/code-temp/remix-gospel-stack/apps/**/remix.config.js
    at /Users/myuser/code-temp/remix-gospel-stack/node_modules/replace-in-file/lib/helpers/glob-async.js:23:23
    at f (/Users/myuser/code-temp/remix-gospel-stack/node_modules/once/once.js:25:25)
    at Glob.<anonymous> (/Users/myuser/code-temp/remix-gospel-stack/node_modules/replace-in-file/node_modules/glob/glob.js:148:7)
    at Glob.emit (node:events:514:28)
    at Glob._finish (/Users/myuser/code-temp/remix-gospel-stack/node_modules/replace-in-file/node_modules/glob/glob.js:194:8)
    at done (/Users/myuser/code-temp/remix-gospel-stack/node_modules/replace-in-file/node_modules/glob/glob.js:179:14)
    at Glob._processSimple2 (/Users/myuser/code-temp/remix-gospel-stack/node_modules/replace-in-file/node_modules/glob/glob.js:688:12)
    at /Users/myuser/code-temp/remix-gospel-stack/node_modules/replace-in-file/node_modules/glob/glob.js:676:10
    at Glob._stat2 (/Users/myuser/code-temp/remix-gospel-stack/node_modules/replace-in-file/node_modules/glob/glob.js:772:12)
    at lstatcb_ (/Users/myuser/code-temp/remix-gospel-stack/node_modules/replace-in-file/node_modules/glob/glob.js:764:12)
    at RES (/Users/myuser/code-temp/remix-gospel-stack/node_modules/inflight/inflight.js:31:16)
    at f (/Users/myuser/code-temp/remix-gospel-stack/node_modules/once/once.js:25:25)
    at FSReqCallback.oncomplete (node:fs:199:21)

  ```

**Comment by PhilDL** [comment]
@ctrlShiftBryan thank you for that report, indeed since the upgrade to vite I forgot to update the `remix.init` folder files and `remix.config.js` doesn't exist anymore.

If you or anyone else would be down to fix that, I would gladly merge the PR, change should be limited to `remix.init/index.js` file.
